import type { LabResult, LabScenarioPayload } from './types';

const wait = (ms = 500) => new Promise((resolve) => setTimeout(resolve, ms));

export const simulationProvider = {
  async runLabScenario(payload: LabScenarioPayload): Promise<LabResult> {
    await wait();
    const cat = payload.bipNumber === 347;
    const valid = payload.scenarioId !== 'failure';
    const scenarioName = cat ? 'OP_CAT concatenation check' : 'CTV template commitment check';
    const expectedBehavior = cat
      ? 'Concatenate the top two stack elements and compare the result against the expected commitment.'
      : 'Recompute the transaction template hash and verify it against the script commitment.';
    const sourceUrl = `https://github.com/bitcoin/bips/blob/master/bip-${payload.bipNumber}.mediawiki`;

    return {
      status: valid ? 'passed' : 'failed',
      scenarioName,
      bipNumber: payload.bipNumber,
      inputs: payload.input,
      expectedBehavior,
      title: valid ? 'Simulated result: scenario passed' : 'Simulated result: validation failed as expected',
      explanation: cat
        ? 'The simulator concatenated two bounded stack elements and compared the result with the expected commitment.'
        : 'The simulator recomputed the transaction template hash and checked it against the script commitment.',
      logs: cat
        ? ['[stack] push 0x6a757374', '[stack] push 0x61736b', '[op] OP_CAT → 0x6a75737461736b', `[verify] ${valid ? 'equal' : 'mismatch'}`]
        : ['[tx] serialize template fields', '[hash] sha256(template)', '[script] OP_CHECKTEMPLATEVERIFY', `[verify] ${valid ? 'commitment matched' : 'commitment mismatch'}`],
      output: valid ? 'TRUE (spend accepted by simulated rules)' : 'FALSE (spend rejected by simulated rules)',
      citation: {
        id: `bip-${payload.bipNumber}-simulation`,
        label: `BIP ${payload.bipNumber}`,
        section: 'Source',
        url: sourceUrl,
        excerpt: 'This result is generated by an educational simulation, not Bitcoin Core.',
      },
    };
  },
};
